name: "Pull Data"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Pull
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v2
      - name: Run pull-steward.sh
        run: bash ./sciprts/pull-steward.sh
